.TL
Spin Testing Log
.AU
Keanu Clark
.AB
These logs are for reporting on exercies inspired by the reading of Gerard Holzmann's Spin Model Checker Primer and Reference Manual IBSN 0-321-77371-3. Concurrency is a natural feature of the world we endure, live, and die in. To model it is to approach succintess and depth of expression without losing potency. May we find new strength in these manners of speaking and declaring exactly what may not be spoken in our games among these meta languages.
.AE
.SH
Hello World
.PP
Chapter 2 pp9, in homage to the first C programming manual authored by Kernighan and Ritchie in 1978, opens with a demonstration of printing 'Hello World'. cf hello-world.pml
